# Generated by Django 4.2.8 on 2024-05-29 15:22

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCharge',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_type', models.CharField(max_length=100)),
                ('service_charge', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=65)),
            ],
        ),
    ]
