# Generated by Django 4.1.7 on 2023-04-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='collection_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
