# Generated by Django 4.2.8 on 2024-02-27 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='collector',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.collectorprofile'),
        ),
    ]
