# Generated by Django 4.1.7 on 2023-03-27 14:05

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10),
        ),
        migrations.AddField(
            model_name='subscription',
            name='sub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
