# Generated by Django 4.1.7 on 2023-04-26 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_collection_collection_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
    ]
