# Generated by Django 4.2.2 on 2023-06-17 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0006_alter_collection_user_alter_subscription_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collectors',
            fields=[
                ('collector_id', models.AutoField(primary_key=True, serialize=False)),
                ('vehicle', models.TextField(max_length=200)),
                ('work_area', models.TextField(max_length=200)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='collection',
            name='user_collect_date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('assigned_date', models.DateTimeField(blank=True)),
                ('date_closed', models.DateTimeField(blank=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.collection')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.collectors')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userprofile')),
            ],
        ),
    ]
