# Generated by Django 4.2.2 on 2023-06-17 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_collectors_alter_collection_user_collect_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
