# Generated by Django 4.2.2 on 2023-06-17 12:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_taskassignment_date_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskassignment',
            name='assigned_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
